import fs from "node:fs";
import path from "node:path";

// Generates src/webHtml.ts + src/webAssets.ts from web/dist so the compiled
// bun binary carries the dashboard with no filesystem dependency.

const webDist = path.join(process.cwd(), "web", "dist");
const srcDir = path.join(process.cwd(), "src");

const htmlPath = path.join(webDist, "index.html");
if (!fs.existsSync(htmlPath)) {
  console.error("error  web/dist/index.html missing — run vite build first");
  process.exit(1);
}

const html = fs.readFileSync(htmlPath, "utf8");
fs.writeFileSync(
  path.join(srcDir, "webHtml.ts"),
  `// generated by scripts/build-embed.mjs — do not edit\nexport const webHtml: string = ${JSON.stringify(html)};\n`,
);

const assetsDir = path.join(webDist, "assets");
const entries = fs.existsSync(assetsDir) ? fs.readdirSync(assetsDir) : [];
const map = {};
for (const f of entries) map[f] = fs.readFileSync(path.join(assetsDir, f), "utf8");
fs.writeFileSync(
  path.join(srcDir, "webAssets.ts"),
  `// generated by scripts/build-embed.mjs — do not edit\nexport const webAssets: Record<string, string> = ${JSON.stringify(map)};\n`,
);

console.log(`embedded ${html.length}B html + ${entries.length} assets`);