// generated by scripts/build-embed.mjs — do not edit
export const webHtml: string = "<!doctype html><html><head><meta charset=\"utf-8\"><title>QuotaCap</title>  <script type=\"module\" crossorigin src=\"/assets/index-C7g0JA14.js\"></script>\n</head><body><div id=\"app\"></div></body></html>\n";
